# Generated by Django 3.0.1 on 2019-12-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
